### PR TITLE
Fix hit and hold for OsuToQua #37

### PR DESCRIPTION
**Pull request by Bestfast**
Alright, I'm not really sure how I should handle this. In this way it works, and since I will only convert from osu! to Quaver it might be fine as well, but since it's your repository I think it should be handled differently, and I think this one is a workaround and not really a fix.
I'm not really into any other VSRG and I don't know how other Rhythm Games handle float hit, holds, various offset etc. 

My other suggestions were: 
Change how it's directly handled in TimedList.py (reamber.base.lists.TimedList) or Timed.py (from reamber.base.Timed import Timed) and convert everything to int there. 
The other one was doing it in QuaHit.py and QuaHold.py, doing it this way it will be ONLY for Quaver.

If you have any other idea, or want me to change it, just comment it here. If it's fine this way, you can merge it freely if you want to. I'm happy to support this project and I'm really interested to see how the project will go!!

### CODE REVIEW

**Comment by Eve-ning** [comment]
other games like SM technically handle floats (they use divisions of measures) prefer not to handle it on the TimedList and only for Quaver, I will check this PR sometime later

also, rerouting it to 0.0.20 since I'm planning to update some stuff

**Comment by Eve-ning** [comment]
not too sure what's the issue on #37? I loaded it fine
```
from reamber.quaver import QuaMap
q = QuaMap.readFile("a.qua")
q.writeFile("b.qua")
q = QuaMap.readFile("b.qua")
```

**Comment by Bestfast** [comment]
If HitObjects StartTime are a float, the game will refuse to parse the file. When converting from osu! to Quaver (I'm unsure if this happens in other circumstances or only here), the output file is invalid. 

[Here](https://hastebin.com/ifebufoyaq.yaml)'s a chart converted from osu! to Quaver with the latest release of reamberPy(invalid file, the parser crashes), while [here](https://hastebin.com/degederuji.yaml) is the same chart after my PR. 

You can also confirm this by looking at other Quaver charts.

[This](https://eve-ning.github.io/reamberPy/reamber/algorithms/convert.html?highlight=convert#id4) is what I used to convert that chart, but I might be wrong on something tho

**Comment by Eve-ning** [comment]
As mentioned in the description of the commit, I've moved the casting from OsuToQua to QuaHit/QuaHold, which is more universal and is more specific.

This allows me to avoid changing any other XXToQua conversions if the issues only lies with floating precision

**Pull request merged**
